// Generated by scripts/build-tokens.mjs
// Do not edit directly. Edit tokens/*.json and run pnpm build:tokens.

export declare const color: {
  readonly neutral: {
    readonly "50": string;
    readonly "100": string;
    readonly "200": string;
    readonly "300": string;
    readonly "400": string;
    readonly "500": string;
    readonly "600": string;
    readonly "700": string;
    readonly "800": string;
    readonly "900": string;
    readonly "950": string;
  };
  readonly coral: {
    readonly "50": string;
    readonly "100": string;
    readonly "200": string;
    readonly "300": string;
    readonly "400": string;
    readonly "500": string;
    readonly "600": string;
    readonly "700": string;
    readonly "800": string;
    readonly "900": string;
  };
  readonly success: {
    readonly "50": string;
    readonly "100": string;
    readonly "200": string;
    readonly "300": string;
    readonly "400": string;
    readonly "500": string;
    readonly "600": string;
    readonly "700": string;
    readonly "800": string;
    readonly "900": string;
  };
  readonly warning: {
    readonly "50": string;
    readonly "100": string;
    readonly "200": string;
    readonly "300": string;
    readonly "400": string;
    readonly "500": string;
    readonly "600": string;
    readonly "700": string;
    readonly "800": string;
    readonly "900": string;
  };
  readonly danger: {
    readonly "50": string;
    readonly "100": string;
    readonly "200": string;
    readonly "300": string;
    readonly "400": string;
    readonly "500": string;
    readonly "600": string;
    readonly "700": string;
    readonly "800": string;
    readonly "900": string;
  };
  readonly info: {
    readonly "50": string;
    readonly "100": string;
    readonly "200": string;
    readonly "300": string;
    readonly "400": string;
    readonly "500": string;
    readonly "600": string;
    readonly "700": string;
    readonly "800": string;
    readonly "900": string;
  };
};
export declare const surface: {
  readonly page: string;
  readonly raised: string;
  readonly sunken: string;
  readonly overlay: string;
};
export declare const border: {
  readonly subtle: string;
  readonly default: string;
  readonly strong: string;
};
export declare const text: {
  readonly primary: string;
  readonly secondary: string;
  readonly tertiary: string;
  readonly inverse: string;
  readonly link: string;
};
export declare const accent: {
  readonly default: string;
  readonly hover: string;
  readonly active: string;
  readonly "on-accent": string;
  readonly "subtle-bg": string;
  readonly "subtle-fg": string;
};
export declare const focus: {
  readonly ring: string;
};
export declare const feedback: {
  readonly success: {
    readonly default: string;
    readonly "subtle-bg": string;
    readonly "subtle-fg": string;
  };
  readonly warning: {
    readonly default: string;
    readonly "subtle-bg": string;
    readonly "subtle-fg": string;
  };
  readonly danger: {
    readonly default: string;
    readonly solid: string;
    readonly "solid-hover": string;
    readonly "subtle-bg": string;
    readonly "subtle-fg": string;
  };
  readonly info: {
    readonly default: string;
    readonly "subtle-bg": string;
    readonly "subtle-fg": string;
  };
};
export declare const font: {
  readonly sans: string;
  readonly mono: string;
};
export declare const fontWeight: {
  readonly regular: string;
  readonly medium: string;
  readonly semibold: string;
};
export declare const fontSize: {
  readonly xs: string;
  readonly sm: string;
  readonly base: string;
  readonly lg: string;
  readonly xl: string;
  readonly "2xl": string;
  readonly "3xl": string;
  readonly "4xl": string;
};
export declare const lineHeight: {
  readonly tight: string;
  readonly snug: string;
  readonly normal: string;
  readonly relaxed: string;
};
export declare const letterSpacing: {
  readonly tighter: string;
  readonly tight: string;
  readonly normal: string;
  readonly wide: string;
};
export declare const space: {
  readonly "0": string;
  readonly "1": string;
  readonly "2": string;
  readonly "3": string;
  readonly "4": string;
  readonly "5": string;
  readonly "6": string;
  readonly "8": string;
  readonly "10": string;
  readonly "12": string;
  readonly "16": string;
  readonly "20": string;
  readonly "24": string;
  readonly "32": string;
  readonly "0.5": string;
  readonly "1.5": string;
};
export declare const radius: {
  readonly none: string;
  readonly xs: string;
  readonly sm: string;
  readonly md: string;
  readonly lg: string;
  readonly xl: string;
  readonly "2xl": string;
  readonly full: string;
};
export declare const shadow: {
  readonly none: string;
  readonly xs: string;
  readonly sm: string;
  readonly md: string;
  readonly lg: string;
  readonly xl: string;
  readonly "2xl": string;
};
export declare const duration: {
  readonly instant: string;
  readonly fast: string;
  readonly normal: string;
  readonly slow: string;
  readonly slower: string;
};
export declare const easing: {
  readonly linear: string;
  readonly out: string;
  readonly in: string;
  readonly "in-out": string;
  readonly spring: string;
};

export declare const v: {
  readonly color: typeof color;
  readonly surface: typeof surface;
  readonly border: typeof border;
  readonly text: typeof text;
  readonly accent: typeof accent;
  readonly focus: typeof focus;
  readonly feedback: typeof feedback;
  readonly font: typeof font;
  readonly fontWeight: typeof fontWeight;
  readonly fontSize: typeof fontSize;
  readonly lineHeight: typeof lineHeight;
  readonly letterSpacing: typeof letterSpacing;
  readonly space: typeof space;
  readonly radius: typeof radius;
  readonly shadow: typeof shadow;
  readonly duration: typeof duration;
  readonly easing: typeof easing;
};
