// Generated by scripts/build-tokens.mjs
// Do not edit directly. Edit tokens/*.json and run pnpm build:tokens.

export const color = {
  neutral: {
    "50": "var(--color-neutral-50)",
    "100": "var(--color-neutral-100)",
    "200": "var(--color-neutral-200)",
    "300": "var(--color-neutral-300)",
    "400": "var(--color-neutral-400)",
    "500": "var(--color-neutral-500)",
    "600": "var(--color-neutral-600)",
    "700": "var(--color-neutral-700)",
    "800": "var(--color-neutral-800)",
    "900": "var(--color-neutral-900)",
    "950": "var(--color-neutral-950)",
  },
  coral: {
    "50": "var(--color-coral-50)",
    "100": "var(--color-coral-100)",
    "200": "var(--color-coral-200)",
    "300": "var(--color-coral-300)",
    "400": "var(--color-coral-400)",
    "500": "var(--color-coral-500)",
    "600": "var(--color-coral-600)",
    "700": "var(--color-coral-700)",
    "800": "var(--color-coral-800)",
    "900": "var(--color-coral-900)",
  },
  success: {
    "50": "var(--color-success-50)",
    "100": "var(--color-success-100)",
    "200": "var(--color-success-200)",
    "300": "var(--color-success-300)",
    "400": "var(--color-success-400)",
    "500": "var(--color-success-500)",
    "600": "var(--color-success-600)",
    "700": "var(--color-success-700)",
    "800": "var(--color-success-800)",
    "900": "var(--color-success-900)",
  },
  warning: {
    "50": "var(--color-warning-50)",
    "100": "var(--color-warning-100)",
    "200": "var(--color-warning-200)",
    "300": "var(--color-warning-300)",
    "400": "var(--color-warning-400)",
    "500": "var(--color-warning-500)",
    "600": "var(--color-warning-600)",
    "700": "var(--color-warning-700)",
    "800": "var(--color-warning-800)",
    "900": "var(--color-warning-900)",
  },
  danger: {
    "50": "var(--color-danger-50)",
    "100": "var(--color-danger-100)",
    "200": "var(--color-danger-200)",
    "300": "var(--color-danger-300)",
    "400": "var(--color-danger-400)",
    "500": "var(--color-danger-500)",
    "600": "var(--color-danger-600)",
    "700": "var(--color-danger-700)",
    "800": "var(--color-danger-800)",
    "900": "var(--color-danger-900)",
  },
  info: {
    "50": "var(--color-info-50)",
    "100": "var(--color-info-100)",
    "200": "var(--color-info-200)",
    "300": "var(--color-info-300)",
    "400": "var(--color-info-400)",
    "500": "var(--color-info-500)",
    "600": "var(--color-info-600)",
    "700": "var(--color-info-700)",
    "800": "var(--color-info-800)",
    "900": "var(--color-info-900)",
  },
};
export const surface = {
  page: "var(--surface-page)",
  raised: "var(--surface-raised)",
  sunken: "var(--surface-sunken)",
  overlay: "var(--surface-overlay)",
};
export const border = {
  subtle: "var(--border-subtle)",
  default: "var(--border-default)",
  strong: "var(--border-strong)",
};
export const text = {
  primary: "var(--text-primary)",
  secondary: "var(--text-secondary)",
  tertiary: "var(--text-tertiary)",
  inverse: "var(--text-inverse)",
  link: "var(--text-link)",
};
export const accent = {
  default: "var(--accent-default)",
  hover: "var(--accent-hover)",
  active: "var(--accent-active)",
  "on-accent": "var(--accent-on-accent)",
  "subtle-bg": "var(--accent-subtle-bg)",
  "subtle-fg": "var(--accent-subtle-fg)",
};
export const focus = {
  ring: "var(--focus-ring)",
};
export const feedback = {
  success: {
    default: "var(--feedback-success-default)",
    "subtle-bg": "var(--feedback-success-subtle-bg)",
    "subtle-fg": "var(--feedback-success-subtle-fg)",
  },
  warning: {
    default: "var(--feedback-warning-default)",
    "subtle-bg": "var(--feedback-warning-subtle-bg)",
    "subtle-fg": "var(--feedback-warning-subtle-fg)",
  },
  danger: {
    default: "var(--feedback-danger-default)",
    solid: "var(--feedback-danger-solid)",
    "solid-hover": "var(--feedback-danger-solid-hover)",
    "subtle-bg": "var(--feedback-danger-subtle-bg)",
    "subtle-fg": "var(--feedback-danger-subtle-fg)",
  },
  info: {
    default: "var(--feedback-info-default)",
    "subtle-bg": "var(--feedback-info-subtle-bg)",
    "subtle-fg": "var(--feedback-info-subtle-fg)",
  },
};
export const font = {
  sans: "var(--font-sans)",
  mono: "var(--font-mono)",
};
export const fontWeight = {
  regular: "var(--font-weight-regular)",
  medium: "var(--font-weight-medium)",
  semibold: "var(--font-weight-semibold)",
};
export const fontSize = {
  xs: "var(--font-size-xs)",
  sm: "var(--font-size-sm)",
  base: "var(--font-size-base)",
  lg: "var(--font-size-lg)",
  xl: "var(--font-size-xl)",
  "2xl": "var(--font-size-2xl)",
  "3xl": "var(--font-size-3xl)",
  "4xl": "var(--font-size-4xl)",
};
export const lineHeight = {
  tight: "var(--line-height-tight)",
  snug: "var(--line-height-snug)",
  normal: "var(--line-height-normal)",
  relaxed: "var(--line-height-relaxed)",
};
export const letterSpacing = {
  tighter: "var(--letter-spacing-tighter)",
  tight: "var(--letter-spacing-tight)",
  normal: "var(--letter-spacing-normal)",
  wide: "var(--letter-spacing-wide)",
};
export const space = {
  "0": "var(--space-0)",
  "1": "var(--space-1)",
  "2": "var(--space-2)",
  "3": "var(--space-3)",
  "4": "var(--space-4)",
  "5": "var(--space-5)",
  "6": "var(--space-6)",
  "8": "var(--space-8)",
  "10": "var(--space-10)",
  "12": "var(--space-12)",
  "16": "var(--space-16)",
  "20": "var(--space-20)",
  "24": "var(--space-24)",
  "32": "var(--space-32)",
  "0.5": "var(--space-0-5)",
  "1.5": "var(--space-1-5)",
};
export const radius = {
  none: "var(--radius-none)",
  xs: "var(--radius-xs)",
  sm: "var(--radius-sm)",
  md: "var(--radius-md)",
  lg: "var(--radius-lg)",
  xl: "var(--radius-xl)",
  "2xl": "var(--radius-2xl)",
  full: "var(--radius-full)",
};
export const shadow = {
  none: "var(--shadow-none)",
  xs: "var(--shadow-xs)",
  sm: "var(--shadow-sm)",
  md: "var(--shadow-md)",
  lg: "var(--shadow-lg)",
  xl: "var(--shadow-xl)",
  "2xl": "var(--shadow-2xl)",
};
export const duration = {
  instant: "var(--duration-instant)",
  fast: "var(--duration-fast)",
  normal: "var(--duration-normal)",
  slow: "var(--duration-slow)",
  slower: "var(--duration-slower)",
};
export const easing = {
  linear: "var(--easing-linear)",
  out: "var(--easing-out)",
  in: "var(--easing-in)",
  "in-out": "var(--easing-in-out)",
  spring: "var(--easing-spring)",
};

export const v = { color, surface, border, text, accent, focus, feedback, font, fontWeight, fontSize, lineHeight, letterSpacing, space, radius, shadow, duration, easing };
